### ISSUE TITLE
Workflow (What to do with the datasets, etc, goals and to-do's)

### ISSUE THREAD

**Issue by avrabyt** [HitMonk/Hidex-parser#1]
Hi @HitMonk , It would be great if you share some of R codes you have previosuly used (if any) , in that way it would be easier for me to get an overall idea. I'm creating it also as one of the To-do's 

- [ ] R codes if there 
- [ ] Python Implementation
- [ ] Workflow for easy understanding and collaboration
- [ ] Elanborate the Readme 
- [ ] What to do and what to implement 

You can leave them as an issue if you wish .

**Comment by HitMonk** [comment]
> Hi @HitMonk , It would be great if you share some of R codes you have previosuly used (if any) , in that way it would be easier for me to get an overall idea. I'm creating it also as one of the To-do's
>     * [ ]  Python Implementation
Im starting on this too. but i think itll be better if we worked on this together. Ill send across what little code i have so far. 

>     * [ ]  Workflow for easy understanding and collaboration
> 
>     * [ ]  Elaborate the Readme
 Mostly done, wrote a short protocol of what we need to do with the dataset files.

>     * [ ]  What to do and what to implement
The readme has an outline now. we can build it out more once we have a working code for 1 file. 

> You can leave them as an issue if you wish .

**Comment by HitMonk** [comment]
The data needs to grouped based on 
- Sample name 
- Sort by `dates`
- Plot growth curve by `date` and `wells`
